export const routes = {
  home: '/',
  login: '/login',
  ventas: '/ventas',
  ventasHistorial: '/ventas/historial',
  productos: '/productos',
  stock: '/stock',
  cierre: '/cierre',
  cierreHistorial: '/cierre/historial',
  sucursales: '/sucursales',
  usuarios: '/usuarios',
  videos: '/videos',
  videosNuevo: '/videos/nuevo',
  videoDetalle: '/videos/[id]',
  pedido: '/pedido',
  pedidos: '/pedidos',
  pedidoDetalle: (id: number | string) => `/pedidos/${id}`,
} as const;
