export const routes = {
  home: '/',
  login: '/login',
  sesionFinalizada: '/sesion-finalizada',
  ventas: '/ventas',
  ventasHistorial: '/ventas/historial',
  ventasHistorialEliminadas: '/ventas/historial/eliminadas',
  productos: '/productos',
  productosNuevo: '/productos/nuevo',
  productosEditar: (id: number | string) => `/productos/${id}/editar`,
  productosEliminados: '/productos/eliminados',
  stock: '/stock',
  cierre: '/cierre',
  reportes: '/reportes',
  sucursales: '/sucursales',
  sucursalesNueva: '/sucursales/nueva',
  sucursalesEditar: (id: number | string) => `/sucursales/${id}/editar`,
  usuarios: '/usuarios',
  usuariosNuevo: '/usuarios/nuevo',
  usuariosEditar: (id: number | string) => `/usuarios/${id}/editar`,
  videos: '/videos',
  videosNuevo: '/videos/nuevo',
  videosEliminados: '/videos/eliminados',
  videoDetalle: (id: number | string) => `/videos/${id}`,
  perfil: '/perfil',
  pedido: '/pedido',
  pedidoSeguimiento: '/pedido/seguimiento',
  pedidos: '/pedidos',
  pedidoDetalle: (id: number | string) => `/pedidos/${id}`,
  pedidoChat: (id: number | string, token: string) =>
    `/pedido/${id}/chat?token=${encodeURIComponent(token)}`,
} as const;
